export  const Data = [
  {
    name: "Essence Mascara Lash Princess",
    img: "https://picsum.photos/id/1011/400/400",
    offer: "20% OFF",
    url: "https://dummyjson.com/products/1",
    price: "$9.99",
  },
  {
    name: "Eyeshadow Palette",
    img: "https://picsum.photos/id/1025/400/400",
    offer: "15% OFF",
    url: "https://dummyjson.com/products/2",
    price: "$19.99",
  },
  {
    name: "Face Powder",
    img: "https://picsum.photos/id/1035/400/400",
    offer: "10% OFF",
    url: "https://dummyjson.com/products/3",
    price: "$14.99",
  },
  {
    name: "Red Lipstick",
    img: "https://picsum.photos/id/1040/400/400",
    offer: "30% OFF",
    url: "https://dummyjson.com/products/4",
    price: "$12.99",
  },
  {
    name: "Calvin Klein CK One",
    img: "https://picsum.photos/id/1050/400/400",
    offer: "18% OFF",
    url: "https://dummyjson.com/products/5",
    price: "$49.99",
  },
  {
    name: "Chanel Coco Noir",
    img: "https://picsum.photos/id/1060/400/400",
    offer: "25% OFF",
    url: "https://dummyjson.com/products/6",
    price: "$129.99",
  },
  {
    name: "Dior J'adore",
    img: "https://picsum.photos/id/1070/400/400",
    offer: "22% OFF",
    url: "https://dummyjson.com/products/7",
    price: "$109.99",
  },
  {
    name: "Gucci Bloom",
    img: "https://picsum.photos/id/1080/400/400",
    offer: "12% OFF",
    url: "https://dummyjson.com/products/8",
    price: "$99.99",
  },
  {
    name: "Apple",
    img: "https://picsum.photos/id/1084/400/400",
    offer: "5% OFF",
    url: "https://dummyjson.com/products/9",
    price: "$2.99",
  },
  {
    name: "Beef Steak",
    img: "https://picsum.photos/id/1081/400/400",
    offer: "8% OFF",
    url: "https://dummyjson.com/products/10",
    price: "$12.99",
  },
  {
    name: "Cat Food",
    img: "https://picsum.photos/id/1082/400/400",
    offer: "20% OFF",
    url: "https://dummyjson.com/products/11",
    price: "$8.49",
  },
  {
    name: "Chicken Meat",
    img: "https://picsum.photos/id/1083/400/400",
    offer: "10% OFF",
    url: "https://dummyjson.com/products/12",
    price: "$9.99",
  },
  {
    name: "Cucumber",
    img: "https://picsum.photos/id/1085/400/400",
    offer: "15% OFF",
    url: "https://dummyjson.com/products/13",
    price: "$1.99",
  },
  {
    name: "Dog Food",
    img: "https://picsum.photos/id/1089/400/400",
    offer: "18% OFF",
    url: "https://dummyjson.com/products/14",
    price: "$11.99",
  },
  {
    name: "Eggs",
    img: "https://picsum.photos/id/109/400/400",
    offer: "7% OFF",
    url: "https://dummyjson.com/products/15",
    price: "$3.99",
  },
  {
    name: "Fish Steak",
    img: "https://picsum.photos/id/110/400/400",
    offer: "14% OFF",
    url: "https://dummyjson.com/products/16",
    price: "$13.49",
  },
  {
    name: "Green Bell Pepper",
    img: "https://picsum.photos/id/111/400/400",
    offer: "9% OFF",
    url: "https://dummyjson.com/products/17",
    price: "$2.49",
  },
  {
    name: "Green Chili Pepper",
    img: "https://picsum.photos/id/112/400/400",
    offer: "12% OFF",
    url: "https://dummyjson.com/products/18",
    price: "$1.49",
  },
  {
    name: "Honey Jar",
    img: "https://picsum.photos/id/113/400/400",
    offer: "20% OFF",
    url: "https://dummyjson.com/products/19",
    price: "$6.99",
  },
  {
    name: "Ice Cream",
    img: "https://picsum.photos/id/114/400/400",
    offer: "25% OFF",
    url: "https://dummyjson.com/products/20",
    price: "$5.99",
  },
];